#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ~/.local/bin/outlook                                                       |
# +----------------------------------------------------------------------------+
# | Copyright © 2019 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

/bin/google-chrome --app=https://outlook.office365.com --new-window &

exit 0 
